#!/usr/bin/env python2

from gradelib import *

r = Runner()

def matchtest(parent, name, points, *args, **kw):
    def do_test():
        r.match(*args, **kw)
    test(points, name, parent=parent)(do_test)

@test(0, "basic [part1.c]")
def test_part1():
    r.run_test("build/part1")
matchtest(test_part1, "set_to_fifteen", 2, "part1: set_to_fifteen OK")
matchtest(test_part1, "array_sum", 3, "part1: array_sum OK")

@test(0, "point structure [part2.c]")
def test_part2():
    r.run_test("build/part2")
matchtest(test_part2, "set_point", 5, "part2: set_point OK")
matchtest(test_part2, "point_dist", 5, "part2: point_dist OK")

@test(0, "linked list [part3.c]")
def test_part3():
    r.run_test("build/part3")
matchtest(test_part3, "list_insert", 5, "part3: list_insert OK")
matchtest(test_part3, "list_end", 2, "part3: list_end OK")
matchtest(test_part3, "list_size", 3, "part3: list_size OK")
matchtest(test_part3, "list_find", 5, "part3: list_find OK")
matchtest(test_part3, "list_remove", 5, "part3: list_remove OK")

run_tests()
